##### Beginning of file

branches:
    except:
        - gh-pages

env:
    global:
        - JULIA_DEBUG="all"

git:
    depth: 99999999

julia:
    - "1.0"
    - "nightly"

language: julia

matrix:
    allow_failures:
        - julia: "nightly"
    fast_finish: true

notifications:
    email:
        on_success: always # default: change
        on_failure: always # default: always

os:
    - linux
    - osx

############################################################################

script: ./ci/travis/script.sh

##### End of file
