##### Beginning of file

import Pkg
import PredictMDExtra

function _package_list()::Vector{String}
    predictmdextra_package_list::Vector{String} =
        PredictMDExtra._package_list()
    predictmdfull_project_toml::String = package_directory(
        "Project.toml",
        )
    predictmdfull_test_project_toml::String = package_directory(
        "test",
        "Project.toml",
        )
    predictmdfull_package_list::Vector{String} = sort(
        unique(
            strip.(
                vcat(
                    collect(
                        keys(
                            Pkg.TOML.parsefile(
                                predictmdfull_project_toml)["deps"]
                            )
                        ),
                    collect(
                        keys(
                            Pkg.TOML.parsefile(
                                predictmdfull_test_project_toml)["deps"]
                            )
                        ),
                    )
                )
            )
        )
    package_list::Vector{String} = sort(
        unique(
            strip.(
                vcat(
                    predictmdextra_package_list,
                    predictmdfull_package_list,
                    )
                )
            )
        )
    return package_list
end

function _print_list_of_package_imports(io::IO = stdout)::Nothing
    package_list = sort(unique(_package_list()))
    println("##### Beginning of file")
    println()
    println("# Automatically generated by: ")
    println("# PredictMDFull._print_list_of_package_imports()")
    println()
    for i = 1:length(package_list)
        println(io, "import $(package_list[i])",)
    end
    println()
    println("##### End of file")
    return nothing
end

##### End of file
